arm_right_controller_test:
  type: joint_group_ff_controllers/JointGroupEffortFFController
  joints:
  - arm_right_1_joint
  - arm_right_2_joint
  - arm_right_3_joint
  - arm_right_4_joint
  - arm_right_5_joint
  - arm_right_6_joint
  - arm_right_7_joint
  arm_right_1_joint: { pid: {p: 2000.0,  i: 200., d: 20., i_clamp: 200.} }
  arm_right_2_joint: { pid: {p: 2000.0,  i: 200., d: 20., i_clamp: 200.} }
  arm_right_3_joint: { pid: {p: 2000.0,  i: 200., d: 20., i_clamp: 200.} }
  arm_right_4_joint: { pid: {p: 2000.0,  i: 200., d: 20., i_clamp: 200.} }
  arm_right_5_joint: { pid: {p: 2000.0,  i: 200., d: 20., i_clamp: 200.} }
  arm_right_6_joint: { pid: {p: 2000.0,  i: 200., d: 20., i_clamp: 200.} }
  arm_right_7_joint: { pid: {p: 2000.0,  i: 200., d: 20., i_clamp: 200.} }
  # Use a feedforward term to reduce the size of PID gains
  velocity_ff:
    arm_right_1_joint: 1.0
    arm_right_2_joint: 1.0
    arm_right_3_joint: 1.0
    arm_right_4_joint: 1.0
    arm_right_5_joint: 1.0
    arm_right_6_joint: 1.0
    arm_right_7_joint: 1.0
  stop_trajectory_duration: 0.5

arm_left_controller_test:
  type: joint_group_ff_controllers/JointGroupEffortFFController
  joints:
  - arm_left_1_joint
  - arm_left_2_joint
  - arm_left_3_joint
  - arm_left_4_joint
  - arm_left_5_joint
  - arm_left_6_joint
  - arm_left_7_joint
  arm_left_1_joint: { pid: {p: 10000.,  i: 0., d: 0., i_clamp: 0.} }
  arm_left_2_joint: { pid: {p: 10000.,  i: 0., d: 0., i_clamp: 0.} }
  arm_left_3_joint: { pid: {p: 10000.,  i: 0., d: 0., i_clamp: 0.} }
  arm_left_4_joint: { pid: {p: 10000.,  i: 0., d: 0., i_clamp: 0.} }
  arm_left_5_joint: { pid: {p: 10000.,  i: 0., d: 0., i_clamp: 0.} }
  arm_left_6_joint: { pid: {p: 10000.,  i: 0., d: 0., i_clamp: 0.} }
  arm_left_7_joint: { pid: {p: 10000.,  i: 0., d: 0., i_clamp: 0.} }
  # Use a feedforward term to reduce the size of PID gains
  velocity_ff:
    arm_left_1_joint: 1.0
    arm_left_2_joint: 1.0
    arm_left_3_joint: 1.0
    arm_left_4_joint: 1.0
    arm_left_5_joint: 1.0
    arm_left_6_joint: 1.0
    arm_left_7_joint: 1.0
  stop_trajectory_duration: 0.5