left_arm:
  ff_controller:
    type: joint_group_ff_controllers/JointGroupVelocityFFController
    joints:
    - left_shoulder_pan_joint
    - left_shoulder_lift_joint
    - left_elbow_joint
    - left_wrist_1_joint
    - left_wrist_2_joint
    - left_wrist_3_joint
    left_shoulder_pan_joint:  { kp: .1, kp_safe: 100 }
    left_shoulder_lift_joint: { kp: .1, kp_safe: 100 }
    left_elbow_joint:         { kp: .1, kp_safe: 100 }
    left_wrist_1_joint:       { kp: .1, kp_safe: 100 }
    left_wrist_2_joint:       { kp: .1, kp_safe: 100 }
    left_wrist_3_joint:       { kp: .1, kp_safe: 100 }

right_arm:
  ff_controller:
    type: joint_group_ff_controllers/JointGroupVelocityFFController
    joints:
    - right_shoulder_pan_joint
    - right_shoulder_lift_joint
    - right_elbow_joint
    - right_wrist_1_joint
    - right_wrist_2_joint
    - right_wrist_3_joint
    right_shoulder_pan_joint:  { kp: .1, kp_safe: 100 }
    right_shoulder_lift_joint: { kp: .1, kp_safe: 100 }
    right_elbow_joint:         { kp: .1, kp_safe: 100 }
    right_wrist_1_joint:       { kp: .1, kp_safe: 100 }
    right_wrist_2_joint:       { kp: .1, kp_safe: 100 }
    right_wrist_3_joint:       { kp: .1, kp_safe: 100 }